name: "MIT 6.141 Team 5 Project Blog"
description: "For MIT's Robotics: Science & Systems class"
meta_description: "MIT 6.141 Team 5 Project Blog"

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "2,3,4"

highlighter: rouge
logo: false
paginate: 15
baseurl: '/pages/rss2016-team5'
domain_name: 'https://github.mit.edu'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Team 5'
author_bio:     "MIT's 6.141 Team 5 is driven by the following motley assortment of undergraduate student hackers, coders, and EE wizards:<br>Eric Wieser, Ernie Ho, Shi-Ke Xue, Miles Steele, Steven Homberg, and Winter Guerra."

excerpt_separator: <!--more-->
